Feature/sdk
kineticdata/peripherals-netsuite pull request #1
Opened 2022-02-14 14:01 UTC by ChadRehmKineticData

Due to the number of new handlers it would be easier to clone the repo to perform the review.

2022-02-18 21:28 UTC, jackboespflug requested changes
Revert modifications to the builder gem for ALL handlers. I only outlined the changes in 1, but it should be done for all of them.

The readme.md and changelog.md files for the repository weren't updated with this PR, but there should probably be some info about these handlers in those files. Also probably indicate the version 2021_1 of the API is required.

2022-02-18 21:28 UTC, jackboespflug commented on handlers/netsuite_custom_record_create_v1/handler/dependencies.rb
> +end
Instead of modifying the builder gem, we should just require the version file if the VERSION constant still isn't defined.

```
  # Require the library
  require 'builder'
  require 'builder/version' unless defined?(Builder::VERSION)
```

2022-02-18 21:28 UTC, jackboespflug commented on handlers/netsuite_custom_record_create_v1/handler/vendor/GEM_MODIFICATIONS.txt
> +   lib\builder\xmlbase.rb file at line 6.
We should remove the modification from the gem, and then this file should be deleted.

2022-02-18 21:28 UTC, jackboespflug commented on handlers/netsuite_custom_record_create_v1/handler/vendor/builder-3.2.3/lib/builder/xmlbase.rb
> +  VERSION = "3.2.3"
Per the GEM_MODIFICATIONS.TXT file, this line was manually added by us. We should put the gem back to it's original state and update the dependencies.rb file instead.

2022-02-20 21:40 UTC, ChadRehmKineticData commented
Made requested updates, but only tested one handler.  Since all updates were identical it is assumed that all other handlers will also function.

2022-02-21 14:24 UTC, jackboespflug approved these changes

2022-02-21 14:24 UTC, merged